"""Static preset tables for AI model profiles, accuracy profiles, and runtime cost profiles.

To add a new profile, add an entry to the relevant dict here.
Config.__post_init__ validates that the selected profile exists.
"""

# ── AI model profiles ─────────────────────────────────────────────────────────
# Each entry defines the provider, chat model, embedding model, and any
# provider-specific size marker used for context-window scaling in __post_init__.

AI_PROFILE_PRESETS: dict[str, dict[str, str]] = {
    "openai": {
        "ai_provider": "openai",
        "chat_model": "gpt-5.4",
        "embedding_model": "text-embedding-3-large",
        "bedrock_gpt_model_size": "",
    },
    "bedrock-20b": {
        "ai_provider": "bedrock",
        "chat_model": "openai.gpt-oss-20b-1:0",
        "embedding_model": "amazon.titan-embed-text-v2:0",
        "bedrock_gpt_model_size": "20b",
    },
    "bedrock-120b": {
        "ai_provider": "bedrock",
        "chat_model": "openai.gpt-oss-120b-1:0",
        "embedding_model": "amazon.titan-embed-text-v2:0",
        "bedrock_gpt_model_size": "120b",
    },
    "bedrock-claude-sonnet-4-6": {
        "ai_provider": "bedrock",
        "chat_model": "global.anthropic.claude-sonnet-4-6",
        "embedding_model": "amazon.titan-embed-text-v2:0",
        "bedrock_gpt_model_size": "",
    },
    "bedrock-claude-opus-4-6": {
        "ai_provider": "bedrock",
        "chat_model": "global.anthropic.claude-opus-4-6-v1",
        "embedding_model": "amazon.titan-embed-text-v2:0",
        "bedrock_gpt_model_size": "",
    },
}

# ── Accuracy profiles ─────────────────────────────────────────────────────────
# Control retrieval breadth, evidence context size, and output token budgets.
# Model-agnostic: these apply on top of whatever AI profile is selected.
# "high" is the canonical baseline — __post_init__ uses it as the reference
# when deciding whether to apply a non-high preset value.

ACCURACY_PROFILE_PRESETS: dict[str, dict[str, int]] = {
    "vhigh": {
        "top_docs": 3,
        "top_sections_per_doc": 5,
        "max_sections_to_llm": 15,
        "rerank_section_candidates": 15,
        "exact_top_docs": 6,
        "exact_top_sections_per_doc": 5,
        "exact_max_sections_to_llm": 15,
        "exact_rerank_section_candidates": 15,
        "broad_top_docs": 6,
        "broad_top_sections_per_doc": 6,
        "broad_max_sections_to_llm": 8,
        "broad_rerank_section_candidates": 24,
        "max_evidence_snippets_per_section": 5,
        "evidence_snippet_char_limit": 320,
        "embedding_raw_excerpt_chars": 600,
        "answer_context_doc_summary_char_limit": 1000,
        "evidence_chunk_char_limit": 900,
        "evidence_neighboring_units": 5,
        "small_section_full_text_chars": 2500,
        "exact_answer_evidence_char_limit": 2600,
        "broad_answer_evidence_char_limit": 2200,
        "answer_evidence_block_limit_exact": 5,
        "answer_evidence_block_limit_broad": 5,
        "max_recent_messages": 10,
        "doc_summary_input_token_budget": 8000,
        "doc_summary_combine_token_budget": 6500,
        "section_summary_input_token_budget": 5500,
        "min_recursive_summary_token_budget": 550,
        "doc_summary_max_output_tokens": 2400,
        "doc_summary_max_output_tokens_cap": 3600,
        "doc_summary_chunk_max_output_tokens": 3660,
        "section_summary_max_output_tokens": 6660,
        "chat_max_output_tokens": 3600,
        "conversation_summary_max_output_tokens": 3750,
    },
    "high": {
        "top_docs": 3,
        "top_sections_per_doc": 3,
        "max_sections_to_llm": 4,
        "rerank_section_candidates": 12,
        "exact_top_docs": 2,
        "exact_top_sections_per_doc": 4,
        "exact_max_sections_to_llm": 3,
        "exact_rerank_section_candidates": 10,
        "broad_top_docs": 6,
        "broad_top_sections_per_doc": 6,
        "broad_max_sections_to_llm": 8,
        "broad_rerank_section_candidates": 24,
        "max_evidence_snippets_per_section": 3,
        "evidence_snippet_char_limit": 320,
        "embedding_raw_excerpt_chars": 600,
        "answer_context_doc_summary_char_limit": 260,
        "evidence_chunk_char_limit": 900,
        "evidence_neighboring_units": 1,
        "small_section_full_text_chars": 1500,
        "exact_answer_evidence_char_limit": 1600,
        "broad_answer_evidence_char_limit": 1200,
        "answer_evidence_block_limit_exact": 2,
        "answer_evidence_block_limit_broad": 2,
        "max_recent_messages": 6,
        "doc_summary_input_token_budget": 6000,
        "doc_summary_combine_token_budget": 4500,
        "section_summary_input_token_budget": 2500,
        "min_recursive_summary_token_budget": 250,
        "doc_summary_max_output_tokens": 1200,
        "doc_summary_max_output_tokens_cap": 2400,
        "doc_summary_chunk_max_output_tokens": 660,
        "section_summary_max_output_tokens": 660,
        "chat_max_output_tokens": 2700,
        "conversation_summary_max_output_tokens": 750,
    },
    "medium": {
        "top_docs": 2,
        "top_sections_per_doc": 2,
        "max_sections_to_llm": 3,
        "rerank_section_candidates": 8,
        "exact_top_docs": 2,
        "exact_top_sections_per_doc": 3,
        "exact_max_sections_to_llm": 2,
        "exact_rerank_section_candidates": 6,
        "broad_top_docs": 4,
        "broad_top_sections_per_doc": 4,
        "broad_max_sections_to_llm": 5,
        "broad_rerank_section_candidates": 12,
        "max_evidence_snippets_per_section": 2,
        "evidence_snippet_char_limit": 240,
        "embedding_raw_excerpt_chars": 350,
        "answer_context_doc_summary_char_limit": 180,
        "evidence_chunk_char_limit": 650,
        "evidence_neighboring_units": 1,
        "small_section_full_text_chars": 1000,
        "exact_answer_evidence_char_limit": 1100,
        "broad_answer_evidence_char_limit": 850,
        "answer_evidence_block_limit_exact": 1,
        "answer_evidence_block_limit_broad": 2,
        "max_recent_messages": 4,
        "doc_summary_input_token_budget": 4200,
        "doc_summary_combine_token_budget": 3000,
        "section_summary_input_token_budget": 1800,
        "min_recursive_summary_token_budget": 250,
        "doc_summary_max_output_tokens": 840,
        "doc_summary_max_output_tokens_cap": 1500,
        "doc_summary_chunk_max_output_tokens": 480,
        "section_summary_max_output_tokens": 480,
        "chat_max_output_tokens": 1950,
        "conversation_summary_max_output_tokens": 480,
    },
    "low": {
        "top_docs": 2,
        "top_sections_per_doc": 2,
        "max_sections_to_llm": 2,
        "rerank_section_candidates": 5,
        "exact_top_docs": 1,
        "exact_top_sections_per_doc": 2,
        "exact_max_sections_to_llm": 1,
        "exact_rerank_section_candidates": 4,
        "broad_top_docs": 3,
        "broad_top_sections_per_doc": 3,
        "broad_max_sections_to_llm": 3,
        "broad_rerank_section_candidates": 8,
        "max_evidence_snippets_per_section": 1,
        "evidence_snippet_char_limit": 180,
        "embedding_raw_excerpt_chars": 180,
        "answer_context_doc_summary_char_limit": 120,
        "evidence_chunk_char_limit": 450,
        "evidence_neighboring_units": 0,
        "small_section_full_text_chars": 700,
        "exact_answer_evidence_char_limit": 800,
        "broad_answer_evidence_char_limit": 600,
        "answer_evidence_block_limit_exact": 1,
        "answer_evidence_block_limit_broad": 1,
        "max_recent_messages": 3,
        "doc_summary_input_token_budget": 2600,
        "doc_summary_combine_token_budget": 1800,
        "section_summary_input_token_budget": 1200,
        "min_recursive_summary_token_budget": 250,
        "doc_summary_max_output_tokens": 540,
        "doc_summary_max_output_tokens_cap": 960,
        "doc_summary_chunk_max_output_tokens": 360,
        "section_summary_max_output_tokens": 360,
        "chat_max_output_tokens": 1200,
        "conversation_summary_max_output_tokens": 300,
    },
}

# ── Runtime cost profiles ─────────────────────────────────────────────────────
# Applied on top of the accuracy profile to tune per-request cost at runtime
# without touching model selection or ingestion quality.
# "standard" is the baseline; "aggressive" reduces retrieval breadth and
# output size significantly to cut cost at the expense of answer depth.

RUNTIME_COST_PROFILE_PRESETS: dict[str, dict[str, int | bool]] = {
    "standard": {
        "top_docs": 3,
        "top_sections_per_doc": 3,
        "max_sections_to_llm": 4,
        "rerank_section_candidates": 12,
        "exact_top_docs": 2,
        "exact_top_sections_per_doc": 4,
        "exact_max_sections_to_llm": 3,
        "exact_rerank_section_candidates": 10,
        "broad_top_docs": 6,
        "broad_top_sections_per_doc": 6,
        "broad_max_sections_to_llm": 8,
        "broad_rerank_section_candidates": 24,
        "max_evidence_snippets_per_section": 3,
        "answer_context_doc_summary_char_limit": 260,
        "evidence_chunk_char_limit": 900,
        "exact_answer_evidence_char_limit": 1600,
        "broad_answer_evidence_char_limit": 1200,
        "answer_evidence_block_limit_exact": 2,
        "answer_evidence_block_limit_broad": 2,
        "max_recent_messages": 6,
        "summarize_after_turns": 8,
        "chat_max_output_tokens": 2700,
        "conversation_summary_max_output_tokens": 750,
        "include_document_metadata_in_answers": True,
        "include_section_metadata_in_answers": True,
        "include_document_orientation_in_answers": True,
        "include_section_orientation_in_answers": True,
    },
    "aggressive": {
        "top_docs": 1,
        "top_sections_per_doc": 1,
        "max_sections_to_llm": 1,
        "rerank_section_candidates": 4,
        "exact_top_docs": 1,
        "exact_top_sections_per_doc": 1,
        "exact_max_sections_to_llm": 1,
        "exact_rerank_section_candidates": 3,
        "broad_top_docs": 2,
        "broad_top_sections_per_doc": 2,
        "broad_max_sections_to_llm": 2,
        "broad_rerank_section_candidates": 6,
        "max_evidence_snippets_per_section": 1,
        "answer_context_doc_summary_char_limit": 80,
        "evidence_chunk_char_limit": 320,
        "exact_answer_evidence_char_limit": 600,
        "broad_answer_evidence_char_limit": 420,
        "answer_evidence_block_limit_exact": 1,
        "answer_evidence_block_limit_broad": 1,
        "max_recent_messages": 2,
        "summarize_after_turns": 12,
        "chat_max_output_tokens": 660,
        "conversation_summary_max_output_tokens": 240,
        "include_document_metadata_in_answers": False,
        "include_section_metadata_in_answers": False,
        "include_document_orientation_in_answers": False,
        "include_section_orientation_in_answers": False,
    },
}
